### ISSUE TITLE
Problem with port

### ISSUE THREAD

**Issue by skrilax91** [hcgcloud/pterodactyl-onset#1]
Hi,
I've setup an Onset server using your eggs, all is working fine but one think don't work, i've a problem with the file port, i explain, when i go to my server my logs sayed me this :

[2020.02.22-12.49.33]: Received info on package "soundstreamer" with 1 files
﻿[2020.02.22-12.49.33]: Received info on package "i18n" with 3 files
﻿[2020.02.22-12.49.33]: Received info on package "dialogui" with 11 files
﻿[2020.02.22-12.49.33]: Received info on package "cinematicui" with 5 files
﻿[2020.02.22-12.49.33]: Received info on package "onsetrp" with 200 files
﻿[2020.02.22-12.49.33]: Received info on package "salsi" with 33 files
﻿[2020.02.22-12.49.33]: Package "soundstreamer" now downloading C:/Users/leo_b/AppData/Local/Onset/Saved/ServerContent/d1fe00cb7ec2774d3a7728a919e0d53f/soundstreamer/soundstreamer_c.lua (0564fda30966059a8be32df59b46787edd0bb7a49b251878f94f7c0625eb046d) from 144.91.125.130:7775
﻿[2020.02.22-12.49.34]: Got an invalid HTTP response (0) attempting to download "C:/Users/leo_b/AppData/Local/Onset/Saved/ServerContent/d1fe00cb7ec2774d3a7728a919e0d53f/soundstreamer/soundstreamer_c.lua"
﻿[2020.02.22-12.49.34]: Package "soundstreamer" is now in fail state due to error
﻿[2020.02.22-12.49.34]: Package "i18n" now downloading C:/Users/leo_b/AppData/Local/Onset/Saved/ServerContent/d1fe00cb7ec2774d3a7728a919e0d53f/i18n/json.lua (5ddf3a519b9dbd5ef11b27eedf276a6049775d6b1effa9ef64fc1e4e062a1c44) from 144.91.125.130:7775
﻿[2020.02.22-12.49.34]: Got an invalid HTTP response (0) attempting to download "C:/Users/leo_b/AppData/Local/Onset/Saved/ServerContent/d1fe00cb7ec2774d3a7728a919e0d53f/i18n/json.lua"
﻿[2020.02.22-12.49.34]: Package "i18n" is now in fail state due to error
﻿[2020.02.22-12.49.34]: Package "dialogui" now downloading C:/Users/leo_b/AppData/Local/Onset/Saved/ServerContent/d1fe00cb7ec2774d3a7728a919e0d53f/dialogui/json.lua (5ddf3a519b9dbd5ef11b27eedf276a6049775d6b1effa9ef64fc1e4e062a1c44) from 144.91.125.130:7775
﻿[2020.02.22-12.49.34]: Got an invalid HTTP response (0) attempting to download "C:/Users/leo_b/AppData/Local/Onset/Saved/ServerContent/d1fe00cb7ec2774d3a7728a919e0d53f/dialogui/json.lua"
﻿[2020.02.22-12.49.34]: Package "dialogui" is now in fail state due to error
﻿[2020.02.22-12.49.34]: Package "cinematicui" now downloading C:/Users/leo_b/AppData/Local/Onset/Saved/ServerContent/d1fe00cb7ec2774d3a7728a919e0d53f/cinematicui/client.lua (a05fa4b1bd64d6ae3b5c0dcb00a4dade1e01270a029a7232f97db8460c61198b) from 144.91.125.130:7775
﻿[2020.02.22-12.49.34]: Got an invalid HTTP response (0) attempting to download "C:/Users/leo_b/AppData/Local/Onset/Saved/ServerContent/d1fe00cb7ec2774d3a7728a919e0d53f/cinematicui/client.lua"
﻿[2020.02.22-12.49.34]: Package "cinematicui" is now in fail state due to error
﻿[2020.02.22-12.49.34]: Package "onsetrp" now downloading C:/Users/leo_b/AppData/Local/Onset/Saved/ServerContent/d1fe00cb7ec2774d3a7728a919e0d53f/onsetrp/welcome/client.lua (f570b267abaf9b298792ee6002bc9aef79209dc392e7458edaef552e83347615) from 144.91.125.130:7775
﻿[2020.02.22-12.49.34]: Got an invalid HTTP response (0) attempting to download "C:/Users/leo_b/AppData/Local/Onset/Saved/ServerContent/d1fe00cb7ec2774d3a7728a919e0d53f/onsetrp/welcome/client.lua"
﻿[2020.02.22-12.49.34]: Package "onsetrp" is now in fail state due to error
﻿[2020.02.22-12.49.35]: Package "salsi" now downloading C:/Users/leo_b/AppData/Local/Onset/Saved/ServerContent/d1fe00cb7ec2774d3a7728a919e0d53f/salsi/object.lua (a1ed13f653c8bc2522afa791979829a74d680b08282c301343dc01a2a2c674af) from 144.91.125.130:7775
﻿[2020.02.22-12.49.35]: Got an invalid HTTP response (0) attempting to download "C:/Users/leo_b/AppData/Local/Onset/Saved/ServerContent/d1fe00cb7ec2774d3a7728a919e0d53f/salsi/object.lua"
﻿[2020.02.22-12.49.35]: Package "salsi" is now in fail state due to error
and i can't play on it
can you explain me ?

**Comment by TLingC** [comment]
Have you allocated `port-1` and `port-2` to the server?

**Comment by skrilax91** [comment]
How can I do that ?

**Comment by TLingC** [comment]
In your panel, `Admin`, `Servers`, select a server, then `Build Configuration`, `Allocation Management`, `Assign Additional Ports`.

**Comment by skrilax91** [comment]
Yep I’ve assigned port 7776 and 7775

**Comment by TLingC** [comment]
Have you rebuilded the container and restarted the server after assigning?

**Comment by skrilax91** [comment]
Yes, two time, but it’s change nothing, logs that I’ve sended are logs after container rebuild and restart

**Comment by TLingC** [comment]
Try to check the port connectivity.

`wget ip:7775`

**Comment by skrilax91** [comment]
root@vmi335161:~# wget 144.91.125.130:7775
--2020-02-22 14:31:09--  http://144.91.125.130:7775/
Connecting to 144.91.125.130:7775... failed: Connection refused.

**Comment by skrilax91** [comment]
But I’ve been configured pterodactyl to allow accès on this on node on allocation tab

**Comment by skrilax91** [comment]
![6566B973-01EF-46B6-8773-3390B49A8CE9](https://user-images.githubusercontent.com/6585219/75093309-ab84bf80-5580-11ea-956b-63001c1c1116.jpeg)

**Comment by TLingC** [comment]
Maybe you should check if something blocked the connection, like firewall. If the port is open, using `wget/curl` should return `empty response` or `connection reset`, as I just tested.

**Comment by skrilax91** [comment]
I don’t have any firewall, ufw is disable

**Comment by TLingC** [comment]
Try to run
```
wget 172.17.0.1:7775
```
in your daemon.
The ip should be for `docker0`, you can use `ifconfig` to check it.

**Comment by skrilax91** [comment]
Connection refused :(

**Comment by TLingC** [comment]
run
```bash
docker ps
```
and send me the output

**Comment by skrilax91** [comment]
Oh, it’s good it seems like my port was closed I’ve do iptable 7775 and it’s now good
